--- #YAML:1.0
name:                Net-SMS-SMSOnline
version:             0.1
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    Carp:                          0
    LWP::UserAgent:                0
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
